Feed 최적화
team-xquare/xquare-frontend pull request #47
Opened 2023-04-25 12:16 UTC by Mooner510

---

# 개요
현재 Feed를 접속하면 대략 60~80MB의 데이터를 소모합니다.
![image](https://user-images.githubusercontent.com/48984409/234261849-75faf1fa-a710-4a3c-ab55-c7cee148d89c.png)

코드 분석 결과, 피드는 개시된 모든 게시물을 불러와 아직 보여지지도 않은 게시물까지도 모두 로딩하고 있습니다.
이 때문에 제 데이터가 순식간에 다 사라졌습니다 (흑흑)

그래서 Feed에 무한 스크롤 기능과 모두 불러와지기 전 스켈레톤 UI가 표시되도록 수정하고자 합니다.
스켈레톤 UI는 무한 스크롤 시 맨 밑으로 내렸을 때에도 다음 데이터를 불러오기 전 까지 표시됩니다.
![image](https://user-images.githubusercontent.com/48984409/234262734-948de316-d503-4b55-ab3e-58bc044a9ac1.png)

---

# 작업사항
## 스켈레톤 UI
![image](https://user-images.githubusercontent.com/48984409/234262458-95f1f04c-a7a9-4e3a-9f6b-b4675e467090.png)
애니메이션이 포함되어 있습니다. 네.

## 무한 스크롤 (gif 이미지)
![녹화_2023_04_25_21_07_01_19](https://user-images.githubusercontent.com/48984409/234271380-6ef849e9-2568-40bb-8499-cbf21934996d.gif)
무한 스크롤시 필요한 API는 이미 백엔드에 PR 날렸습니다.
백엔드 측 의견을 반영한 후에 프론트 PR을 작성하는 것이기 때문에, No offset을 이용하는 방법으로 다시 재수정하였습니다.

## 댓글 최적화
댓글을 불러올 때 모든 게시물을 불러온 후 필터를 하더라고요.
백엔드 코드에 feedId로 가져오는 API를 추가했습니다.
그런데, 로컬에서 실행했을때 약간의 지연이 발생하는 문제가 있더라고요. 코드 상으로 문제가 있는건지 로컬에서 **백엔드 서버, 프론트 서버, 안드 애뮬레이터** 모두 키고 디버깅해서 그런건지 모르겠지만 아무튼 제 기준으로 지연 문제가 조금 있더라고요.

2023-04-25 13:22 UTC, kimulchan requested changes
안녕하세요 Mooner510! 
저희 Xquare-Frontend에 기여해주셔서 감사드립니다.
몇가지 수정사항만 반영해주시면 기능 올려드리도록 하겠습니다!!
감사합니다!!

2023-04-25 13:22 UTC, kimulchan commented on services/feed/src/main/apis.ts
> +    const feedListKey = queryKeys.getFeedList(categoryId, dateTime);
dateTime 존재 이유를 모르겠습니다!

2023-04-25 13:22 UTC, kimulchan commented on services/feed/src/utils/queryKeys.ts
> +    getFeedList: (categoryId?: string, dateTime?: string) => `?category=${categoryId || ''}${dateTime ? `&dateTime=${dateTime}` : ''}`,
dateTime을 보내서 페이지네이션을 하는 이유를 모르겠습니다.

2023-04-25 13:22 UTC, kimulchan commented on services/feed/src/pages/index.tsx
> +    const feeds = useMemo(() => (dataList ? dataList.pages.flatMap(feed => feed.feeds) : []), [dataList])
infinity query 관련 로직을 하나의 Hook으로 분리하면 좋을 것 같습니다.

2023-04-25 13:22 UTC, kimulchan commented on services/feed/src/pages/index.tsx
> +    const feeds = useMemo(() => (dataList ? dataList.pages.flatMap(feed => feed.feeds) : []), [dataList])
추가로 SSR 적용까지 시키면 좋을 것 같아요!

2023-04-25 13:35 UTC, kimulchan commented
추가로 xquare README에 있는 준비하기를 참고하여 prettier 정리 부탁드립니다!

2023-04-25 14:32 UTC, Mooner510 commented on services/feed/src/main/apis.ts
> +    const feedListKey = queryKeys.getFeedList(categoryId, dateTime);
@kimulchan 
백엔드 측과 DB에 아직 인덱싱이 되어 있지 않기 때문에 page/limit(offset)을 이용한 방법이 아닌 No offset을 이용한 방법을 사용한 것입니다.

모든 게시물의 id는 long이나 int가 아닌, UUID이기 때문에 id로 인덱싱 처리 또는 정렬할 수 없기 때문입니다.

자세한 이용 용도는, 먼저 n개의 게시물을 불러와 보여준 후, 스크롤을 하게 될 경우 가장 마지막으로 불러온 게시물이 올라간 시간 이후의 시간부터 n개의 게시물을 다시 불러오는 방식입니다.

2023-04-25 14:33 UTC, Mooner510 commented on services/feed/src/main/apis.ts
> +    const feedListKey = queryKeys.getFeedList(categoryId, dateTime);
https://github.com/team-xquare/xquare-frontend/pull/47#discussion_r1176609997
위의 게시물과 동일한 답변입니다.

2023-04-25 14:34 UTC, Mooner510 commented on services/feed/src/utils/queryKeys.ts
> +    getFeedList: (categoryId?: string, dateTime?: string) => `?category=${categoryId || ''}${dateTime ? `&dateTime=${dateTime}` : ''}`,
https://github.com/team-xquare/xquare-frontend/pull/47#discussion_r1176609997
위의 게시물과 동일한 답변입니다.

2023-04-25 14:38 UTC, Mooner510 commented on services/feed/src/pages/index.tsx
> +    const feeds = useMemo(() => (dataList ? dataList.pages.flatMap(feed => feed.feeds) : []), [dataList])
네. 일단 제가 가능한 부분만 일단 훅으로 분리한 것 뿐입니다.
꼭 분리하지 않더라도 괜찮을 것 같아 생각해 더 작게 분리하지 않았습니다.

React 등 프론트엔드가 주 개발 분야가 아니어서 전문적인건 잘 몰라 구현이나 설명이 부족할 수 있어 정말 죄송합니다.

2023-04-26 03:28 UTC, Mooner510 commented on services/feed/src/pages/index.tsx
> +                return lastPage.feeds.length == 6 ? lastPage.feeds[lastPage.feeds.length - 1].created_at : undefined;
맨 밑으로 더 이상 불러올 피드가 없을 때 까지 스크롤 할 경우 문제가 발생할 수 있기에 수정하였습니다.
또한, totalPage등의 값 없이 마지막 페이지를 인식할 수 있도록 수정하였습니다.

2023-04-26 10:23 UTC, kimulchan commented
혹시 main 브랜치에서 작업하셨나요??

2023-04-26 10:50 UTC, Mooner510 commented
@kimulchan 
포크한 레포에서 브랜치를 나누어 작업하다 메인으로 병합 후 PR을 날렸는데, 이후 커밋은 아마 main에서 진행된 것 같습니다.
혹시 문제가 되는건가요?

2023-04-27 03:09 UTC, kimulchan commented
제 로컬 환경에서 테스트 해보려 했는데 브랜치 명이 main으로 겹쳐서 그냥 제 로컬 main 브랜치 지우고 실행하였습니다. 다음 부터 브랜치 명을 따로 파서 개발해주시면 감사하겠습니다🙇‍♂️

2023-04-27 03:10 UTC, kimulchan commented on services/feed/src/pages/index.tsx
> +                return lastPage.feeds.length == 6 ? lastPage.feeds[lastPage.feeds.length - 1].created_at : undefined;
이러면 feed length 가 딱 6개로 맞아 떨어지면 다시 불러오는 문제는 똑같이 발생하는것 아닌가요?

2023-04-27 03:14 UTC, kimulchan commented on services/feed/src/pages/index.tsx
> +                return lastPage.feeds.length == 6 ? lastPage.feeds[lastPage.feeds.length - 1].created_at : undefined;
백엔드 쪽에서 마지막 게시물 이라는것을 알 수 있도록 하는 데이터를 같이 보내면 좋을 것 같습니다!

2023-04-27 04:03 UTC, Mooner510 commented on services/feed/src/pages/index.tsx
> +                return lastPage.feeds.length == 6 ? lastPage.feeds[lastPage.feeds.length - 1].created_at : undefined;
> 이러면 feed length 가 딱 6개로 맞아 떨어지면 다시 불러오는 문제는 똑같이 발생하는것 아닌가요?

@kimulchan 
다시 불러오긴 하겠지만, 그러면 돌려주는 게시물이 하나도 없기 때문에 0개가 되어 더 이상 호출하지 않게 됩니다.

만약, 6개가 아닌 마지막인지 판단하는 것을 백엔드에서 사용한다면 전체 피드의 수를 계산해야 하기 때문에 매번 하나의 쿼리를 더 실행해야 합니다.

게시물을 페이징 형식이 아닌 무한스크롤 형식이고 페이지로 나누는 것이 아닌 게시물의 시간을 비교하여 Offset을 사용하지 않기 때문에 전체 크기를 꼭 알 필요가 없습니다.

어차피 게시물을 불러오기 위해서 날짜 계산이 이루어진다면, 마지막까지 프론트에서 한 번 더 요청을 보내어 비어있는지 까지 검사하는 것이 번거로운 연산이 줄어들고 DB에 부담을 조금이라도 줄일 수 있을거라 생각합니다.

2023-04-27 04:07 UTC, Mooner510 commented
@kimulchan 
죄송합니다. 분기를 나누어 작업했었지만, 병합을 시키는 바람에 이후 커밋이 main 브랜치로 옮겨져 PR때도 main 브랜치로 된 것 같습니다.

다음부터 PR을 날리기 전 해당 레포의 메인 브랜치와 이름이 겹치는지 확인하겠습니다.

2023-04-27 23:49 UTC, kimulchan commented on services/feed/src/pages/index.tsx
> +    const feeds = useMemo(() => (dataList ? dataList.pages.flatMap(feed => feed.feeds) : []), [dataList])
이 부분은 제가 한번 더 체크 하겠습니다!

2023-04-27 23:49 UTC, kimulchan commented on services/feed/src/pages/index.tsx
> +                return lastPage.feeds.length == 6 ? lastPage.feeds[lastPage.feeds.length - 1].created_at : undefined;
좋은 것 같습니다! 그러면 제가 확인 후에 머지될 수 있도록 하겠습니다!! 감사합니다

2023-05-04 02:16 UTC, kimulchan reviewed
수고하셨습니다 @Mooner510 !
Xquare 프론트엔드에 기여해주셔서 감사합니다. 이 PR은 바로 배포버전으로 올리겠습니다!

2023-05-04 02:49 UTC, kimulchan approved these changes

2023-05-04 02:49 UTC, merged